from .static import *
from .objects import *
from .community import *
from .ospf import *
from .isis import *
from .eigrp import *
from .bgp import *
from .core import *

__all__ = (
    # Core View Extensions
    'DeviceStaticRoutesView',
    # Static
    'StaticRouteListView',
    'StaticRouteView',
    'StaticRouteDevicesView',
    'StaticRouteEditView',
    'StaticRouteBulkEditView',
    'StaticRouteDeleteView',
    'StaticRouteBulkDeleteView',
    # OSPF
    'OSPFInstanceListView',
    'OSPFInstanceView',
    'OSPFInstanceEditView',
    'OSPFInstanceDeleteView',
    'OSPFInstanceInterfacesView',
    'OSPFAreaListView',
    'OSPFAreaView',
    'OSPFAreaInterfacesView',
    'OSPFAreaEditView',
    'OSPFAreaDeleteView',
    'OSPFInterfaceListView',
    'OSPFInterfaceView',
    'OSPFInterfaceEditView',
    'OSPFInterfaceDeleteView',
    # IS-IS
    'ISISInstanceListView',
    'ISISInstanceView',
    'ISISInstanceEditView',
    'ISISInstanceDeleteView',
    'ISISInstanceBulkEditView',
    'ISISInstanceBulkDeleteView',
    'ISISInstanceBulkImportView',
    'ISISInstanceInterfacesView',
    'ISISInstanceLevelsView',
    'ISISInstanceFlexAlgosView',
    'ISISInstanceSRv6LocatorsView',
    'ISISInterfaceListView',
    'ISISInterfaceView',
    'ISISInterfaceEditView',
    'ISISInterfaceDeleteView',
    'ISISInterfaceBulkEditView',
    'ISISInterfaceBulkDeleteView',
    'ISISInterfaceBulkImportView',
    'ISISInterfaceLevelsView',
    'ISISInterfacePrefixSidsView',
    'ISISPrefixSIDListView',
    'ISISPrefixSIDView',
    'ISISPrefixSIDEditView',
    'ISISPrefixSIDDeleteView',
    'ISISPrefixSIDBulkDeleteView',
    'ISISPrefixSIDBulkImportView',
    'ISISSRv6LocatorListView',
    'ISISSRv6LocatorView',
    'ISISSRv6LocatorEditView',
    'ISISSRv6LocatorDeleteView',
    'ISISSRv6LocatorBulkDeleteView',
    'ISISSRv6LocatorBulkImportView',
    'ISISSettingListView',
    'ISISSettingView',
    'ISISSettingEditView',
    'ISISSettingDeleteView',
    'ISISSettingBulkEditView',
    'ISISSettingBulkDeleteView',
    'ISISSettingBulkImportView',
    'ISISLevelListView',
    'ISISLevelView',
    'ISISLevelEditView',
    'ISISLevelDeleteView',
    'ISISLevelBulkDeleteView',
    'ISISLevelBulkImportView',
    'ISISInterfaceLevelListView',
    'ISISInterfaceLevelView',
    'ISISInterfaceLevelEditView',
    'ISISInterfaceLevelDeleteView',
    'ISISInterfaceLevelBulkDeleteView',
    'ISISInterfaceLevelBulkImportView',
    'ISISSegmentRoutingListView',
    'ISISSegmentRoutingView',
    'ISISSegmentRoutingEditView',
    'ISISSegmentRoutingDeleteView',
    'ISISSegmentRoutingBulkDeleteView',
    'ISISSegmentRoutingBulkImportView',
    'ISISFlexAlgoListView',
    'ISISFlexAlgoView',
    'ISISFlexAlgoEditView',
    'ISISFlexAlgoDeleteView',
    'ISISFlexAlgoBulkDeleteView',
    'ISISFlexAlgoBulkImportView',
    # EIGRP
    'EIGRPRouterListView',
    'EIGRPRouterView',
    'EIGRPRouterInterfacesView',
    'EIGRPRouterEditView',
    'EIGRPRouterImportView',
    'EIGRPRouterBulkEditView',
    'EIGRPRouterDeleteView',
    'EIGRPRouterBulkDeleteView',
    'EIGRPAddressFamilyListView',
    'EIGRPAddressFamilyView',
    'EIGRPAddressFamilyInterfacesView',
    'EIGRPAddressFamilyEditView',
    'EIGRPAddressFamilyBulkEditView',
    'EIGRPAddressFamilyDeleteView',
    'EIGRPAddressFamilyBulkDeleteView',
    'EIGRPNetworkListView',
    'EIGRPNetworkView',
    'EIGRPNetworkEditView',
    'EIGRPNetworkBulkEditView',
    'EIGRPNetworkDeleteView',
    'EIGRPNetworkBulkDeleteView',
    'EIGRPInterfaceListView',
    'EIGRPInterfaceView',
    'EIGRPInterfaceEditView',
    'EIGRPInterfaceBulkEditView',
    'EIGRPInterfaceDeleteView',
    'EIGRPInterfaceBulkDeleteView',
    'BGPRouterView',
    'BGPRouterEditView',
    # Routing Objects
    'CommunityListListView',
    'CommunityListView',
    # 'CommunityListEntriesView',
    'CommunityListEditView',
    'CommunityListDeleteView',
    'CommunityListEntryListView',
    'CommunityListEntryDetailView',
    'CommunityListEntryEditView',
    'CommunityListEntryDeleteView',
    'CommunityListView',
    'CommunityView',
    'CommunityEditView',
    'CommunityDeleteView',
    'PrefixListListView',
    'PrefixListView',
    'PrefixListEntriesView',
    'PrefixListEditView',
    'PrefixListDeleteView',
    'PrefixListEntryListView',
    'PrefixListEntryView',
    'PrefixListEntryEditView',
    'PrefixListEntryDeleteView',
    'PrefixListEntryBulkEditView',
    'PrefixListEntryBulkDeleteView',
    'RouteMapListView',
    'RouteMapView',
    'RouteMapEntriesView',
    'RouteMapEditView',
    'RouteMapDeleteView',
    'RouteMapEntryListView',
    'RouteMapEntryView',
    'RouteMapEntryEditView',
    'RouteMapEntryDeleteView',
    'RouteMapEntryBulkEditView',
    'RouteMapEntryBulkDeleteView',
)
