# Generated by Django 5.0.8 on 2024-09-28 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0012_osfp_instance_vrf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BGPPoliyTemplate',
            new_name='BGPPolicyTemplate',
        ),
        migrations.DeleteModel(
            name='BGPPeer',
        ),
    ]
