# Generated by Django 5.1.8 on 2025-04-22 01:50

import netbox_routing.fields.ip
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0013_staticroute_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticroute',
            name='interface_next_hop',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='next_hop',
            field=netbox_routing.fields.ip.IPAddressField(blank=True, null=True),
        ),
    ]
