# Generated by Django 5.0.9 on 2024-11-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0014_bgppeers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpaddressfamily',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_address_families',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgppeer',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_peers',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgppeeraddressfamily',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_peer_afs',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgppeertemplate',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_peer_templates',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgppolicytemplate',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_peer_policy_templates',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgprouter',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_routers',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgpscope',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_scopes',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='bgpsessiontemplate',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_peer_session_templates',
                to='tenancy.tenant',
            ),
        ),
    ]
