# Generated by Django 5.1.8 on 2025-04-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0014_staticroute_interface_next_hop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfarea',
            name='area_type',
            field=models.CharField(default='standard'),
        ),
    ]
