# Generated by Django 5.0.9 on 2024-11-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_routing', '0015_bgp_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgppeeraddressfamily',
            name='peer_session',
        ),
        migrations.AddField(
            model_name='bgppeeraddressfamily',
            name='peer_policy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='peer_afs',
                to='netbox_routing.bgppolicytemplate',
            ),
        ),
        migrations.AlterField(
            model_name='bgppeeraddressfamily',
            name='assigned_object_type',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(('app_label', 'netbox_routing'), ('model', 'bgppeer')),
                        models.Q(('app_label', 'netbox_routing'), ('model', 'bgptemplatepeer')),
                        _connector='OR',
                    )
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='contenttypes.contenttype',
            ),
        ),
    ]
