# Generated by Django 5.1.8 on 2025-04-23 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0076_natural_ordering'),
        ('netbox_routing', '0015_ospfarea_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfarea',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ospf_areas', to='netbox_routing.ospfinstance'),
        ),
        migrations.AddField(
            model_name='ospfarea',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ospf_areas', to='ipam.vrf'),
        ),
    ]
