# Generated by Django 5.2.2 on 2025-10-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_ospfinterface_interface_onetoonefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfinterface',
            name='neighbor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ospf_neighbors', to='netbox_routing.ospfinterface'),
        ),
    ]
