# Generated by Django 5.2b1 on 2025-07-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_ospfinterface_interface_onetoonefield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BGPPoliyTemplate',
            new_name='BGPPolicyTemplate',
        ),
    ]
