# Generated by Django 5.2.2 on 2025-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_ospfinterface_interface_onetoonefield'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eigrprouter',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_eigrprouter_unique_device_name',
                nulls_distinct=False,
                violation_error_message="""Name must be unique per device.\n
                Only a single empty name is permitted per device""",
            ),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_ospfinstance_unique_device_name',
                nulls_distinct=False,
                violation_error_message="""Name must be unique per device.\n
                Only a single empty name is permitted per device""",
            ),
        ),
    ]
