# Generated by Django 5.2b1 on 2025-07-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_rename_bgppolicytemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefixlistentry',
            old_name='type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='routemapentry',
            old_name='type',
            new_name='action',
        ),
    ]
