# Generated by Django 5.2.8 on 2025-11-21 13:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_routing', '0016_ospfinterface_interface_onetoonefield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrefixList',
            new_name='RoutingPrefixList',
        ),
        migrations.RemoveConstraint(
            model_name='routingprefixlist',
            name='netbox_routing_prefixlist_unique_name',
        ),
        migrations.AddConstraint(
            model_name='routingprefixlist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='netbox_routing_routingprefixlist_unique_name', violation_error_message='Name must be unique.'),
        ),
    ]
