# Generated by Django 5.2.2 on 2025-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
        ('ipam', '0081_remove_service_device_virtual_machine_add_parent_gfk_index'),
        ('netbox_routing', '0015_alter_ospfarea_options_alter_ospfinstance_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eigrprouter',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_eigrprouter_unique_device_name',
                nulls_distinct=False,
                violation_error_message="""Name must be unique per device.\n
                Only a single empty name is permitted per device""",
            ),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_ospfinstance_unique_device_name',
                nulls_distinct=False,
                violation_error_message="""Name must be unique per device.\n
                Only a single empty name is permitted per device""",
            ),
        ),
    ]
