# Generated by Django 5.2.2 on 2025-10-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_ospfinterface_interface_onetoonefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfinterface',
            name='network_type',
            field=models.CharField(default='broadcast'),
        ),
    ]
