# Generated by Django 5.2b1 on 2025-07-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_rename_type_to_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgppeer',
            name='peer_policy',
        ),
        migrations.RemoveField(
            model_name='bgppeeraddressfamily',
            name='peer_session',
        ),
        migrations.AddField(
            model_name='bgppeer',
            name='peer_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='peers',
                to='netbox_routing.bgpsessiontemplate',
            ),
        ),
        migrations.AddField(
            model_name='bgppeeraddressfamily',
            name='peer_policy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='peer_afs',
                to='netbox_routing.bgppolicytemplate',
            ),
        ),
    ]
