# Generated by Django 5.1.8 on 2025-05-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0016_ospfarea_instance_ospfarea_vrf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ospfarea',
            name='vrf',
        ),
    ]
