# Generated by Django 5.2.9 on 2026-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0017_netbox_v040500'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticroute',
            name='interface_next_hop',
            field=models.CharField(blank=True, null=True),
        ),
    ]
