# Generated by Django 5.1.8 on 2025-05-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0017_remove_ospfarea_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfinterface',
            name='network_type',
            field=models.CharField(default='broadcast'),
        ),
    ]
