# Generated by Django 5.2.9 on 2026-01-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0017_netbox_v040500'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospfinterface',
            name='network_type',
            field=models.CharField(default='broadcast'),
        ),
    ]
