# Generated by Django 5.2.9 on 2026-02-17 15:00

import netbox_routing.fields.ip
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0018_staticroute_interface_next_hop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='next_hop',
            field=netbox_routing.fields.ip.IPAddressField(blank=True, null=True),
        ),
    ]
