# Generated by Django 5.2.5 on 2026-01-16 23:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0018_reset_bgp_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefixlistentry',
            old_name='type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='routemapentry',
            old_name='type',
            new_name='action',
        ),
        migrations.AddField(
            model_name='prefixlist',
            name='family',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prefixlistentry',
            name='ge',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(128),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='prefixlistentry',
            name='le',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(128),
                ],
            ),
        ),
    ]
