# Generated by Django 5.2.9 on 2026-02-17 18:07

import django.db.models.deletion
import netbox_routing.fields.ip
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_routing', '0025_prefixlistentry_prefix_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticroute',
            name='interface_next_hop',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='next_hop',
            field=netbox_routing.fields.ip.IPAddressField(blank=True, null=True),
        ),
    ]
