# Generated by Django 5.2.13 on 2026-05-20 04:47

from django.db import migrations, models


VIOLATION_ERROR = "VRF, Prefix, Next Hop, and Device (if set, otherwise ignore this is ignored) must be unique."


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0233_device_render_config_permission"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("ipam", "0089_default_ordering_indexes"),
        ("netbox_routing", "0029_community_name"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="staticroute",
            name="netbox_routing_staticroute_unique_vrf_prefix_nexthop",
        ),
        migrations.AddConstraint(
            model_name="staticroute",
            constraint=models.UniqueConstraint(
                models.F("device"),
                models.F("vrf"),
                models.F("prefix"),
                models.F("next_hop"),
                name="netbox_routing_staticroute_unique_vrf_prefix_nexthop",
                nulls_distinct=False,
                violation_error_message=VIOLATION_ERROR,
            ),
        ),
    ]
