# Generated by Django 5.2.13 on 2026-04-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_routing', '0029_community_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ospfinstance',
            name='device',
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='device_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='device_type',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'model__in': ('device', 'virtualmachine')},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
    ]
