# Generated by Django 5.2.13 on 2026-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0029_community_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staticroute',
            name='netbox_routing_staticroute_unique_vrf_prefix_nexthop',
        ),
    ]
