# Generated by Django 5.2.13 on 2026-04-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        (
            'netbox_routing',
            '0030_remove_ospfinstance_device_ospfinstance_device_id_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ospfinterface',
            options={'ordering': ('instance', 'area')},
        ),
        migrations.RemoveField(
            model_name='ospfinterface',
            name='interface',
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='interface_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='interface_type',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'model__in': ('interface', 'vminterface')},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ospf_interface_type',
                to='contenttypes.contenttype',
            ),
        ),
    ]
