# Generated by Django 5.2.13 on 2026-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0234_cablepath_nodes_index'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0089_default_ordering_indexes'),
        ('netbox_routing', '0031_routing_instance_uniqueness'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eigrpaddressfamily',
            options={'ordering': ['router', 'vrf', 'family', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eigrpinterface',
            options={'ordering': ['router', 'address_family', 'interface', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eigrpnetwork',
            options={'ordering': ['router', 'address_family', 'network', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eigrprouter',
            options={'ordering': ['device', 'name', 'pid', 'rid', 'pk']},
        ),
        migrations.AlterConstraint(
            model_name='eigrprouter',
            name='netbox_routing_eigrprouter_unique_device_name',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_eigrprouter_unique_device_name',
                nulls_distinct=False,
                violation_error_message='Name must be unique per device.',
            ),
        ),
    ]
