# Generated by Django 6.0.5 on 2026-07-07 20:40

import django.core.validators
import django.db.models.deletion
import ipam.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0234_cablepath_nodes_index'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0089_default_ordering_indexes'),
        ('netbox_routing', '0032_fix_eigrp_router_ordering'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISISFlexAlgo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                (
                    'algo_id',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(128),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    'metric_type',
                    models.CharField(blank=True, default='', max_length=40),
                ),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'admin_group_exclude',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'admin_group_include_any',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'admin_group_include_all',
                    models.CharField(blank=True, default='', max_length=200),
                ),
            ],
            options={
                'verbose_name': 'IS-IS Flex-Algo',
                'ordering': ('instance', 'algo_id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISInstance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                (
                    'process_tag',
                    models.CharField(blank=True, default='', max_length=100),
                ),
                ('net', models.CharField(blank=True, default='', max_length=100)),
                ('is_type', models.CharField(blank=True, default='', max_length=50)),
                (
                    'metric_style',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                ('overload_bit', models.BooleanField(blank=True, null=True)),
                (
                    'area_auth_type',
                    models.CharField(blank=True, default='', max_length=16),
                ),
                (
                    'area_auth_key',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                (
                    'domain_auth_type',
                    models.CharField(blank=True, default='', max_length=16),
                ),
                (
                    'domain_auth_key',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                (
                    'spf_initial_wait',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('spf_max_wait', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'lsp_initial_wait',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('lsp_max_wait', models.PositiveIntegerField(blank=True, null=True)),
                ('lsp_lifetime', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'lsp_refresh_interval',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('lsp_mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('overload_on_startup', models.BooleanField(blank=True, null=True)),
                (
                    'overload_timeout',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('suppress_attached_bit', models.BooleanField(blank=True, null=True)),
                ('ignore_attached_bit', models.BooleanField(blank=True, null=True)),
                ('te_enabled', models.BooleanField(blank=True, null=True)),
                (
                    'fast_reroute',
                    models.CharField(blank=True, default='', max_length=16),
                ),
                ('microloop_avoidance', models.BooleanField(blank=True, null=True)),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'maximum_paths',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'reference_bandwidth',
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                'verbose_name': 'IS-IS Instance',
                'ordering': ['device', 'process_tag'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISInterface',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('address_family', models.CharField(max_length=10)),
                (
                    'circuit_type',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                (
                    'network_type',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('passive', models.BooleanField(blank=True, null=True)),
                (
                    'hello_auth_type',
                    models.CharField(blank=True, default='', max_length=16),
                ),
                (
                    'hello_auth_key',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                ('frr_enabled', models.BooleanField(blank=True, null=True)),
                (
                    'frr_protection',
                    models.CharField(blank=True, default='', max_length=8),
                ),
                ('bfd_enabled', models.BooleanField(blank=True, null=True)),
                ('csnp_interval', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'retransmit_interval',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('lsp_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('mesh_group', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'IS-IS Interface',
                'ordering': ('instance', 'interface'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISInterfaceLevel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('hello_interval', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'hello_multiplier',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IS-IS Interface Level',
                'ordering': ('interface', 'level'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISLevel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('default_metric', models.PositiveIntegerField(blank=True, null=True)),
                ('wide_metrics_only', models.BooleanField(blank=True, null=True)),
                ('preference', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'labeled_preference',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('auth_type', models.CharField(blank=True, default='', max_length=16)),
                ('auth_key', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'IS-IS Level',
                'ordering': ('instance', 'level'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISPrefixSID',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('algorithm', models.PositiveSmallIntegerField(default=0)),
                ('sid_index', models.PositiveIntegerField(blank=True, null=True)),
                ('sid_label', models.PositiveIntegerField(blank=True, null=True)),
                ('n_flag', models.BooleanField(blank=True, null=True)),
                ('no_php', models.BooleanField(blank=True, null=True)),
                ('explicit_null', models.BooleanField(blank=True, null=True)),
                ('readvertise', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IS-IS Prefix-SID',
                'ordering': ('interface', 'algorithm'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISSegmentRouting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('srv6_enabled', models.BooleanField(blank=True, null=True)),
                (
                    'prefix_sid_range',
                    models.CharField(blank=True, default='', max_length=32),
                ),
                ('srgb_start', models.PositiveIntegerField(blank=True, null=True)),
                ('srgb_range', models.PositiveIntegerField(blank=True, null=True)),
                ('srlb_start', models.PositiveIntegerField(blank=True, null=True)),
                ('srlb_range', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'maximum_sid_depth',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'tunnel_table_pref',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                'verbose_name': 'IS-IS Segment Routing',
                'verbose_name_plural': 'IS-IS Segment Routing',
                'ordering': ('instance',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISSetting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                (
                    'assigned_object_id',
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'IS-IS Setting',
                'verbose_name_plural': 'IS-IS Settings',
                'ordering': ('assigned_object_type', 'assigned_object_id', 'key'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISSRv6Locator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=64)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('algorithm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_anycast', models.BooleanField(blank=True, null=True)),
                ('is_micro_segment', models.BooleanField(blank=True, null=True)),
                ('flavor', models.CharField(blank=True, default='', max_length=64)),
                (
                    'block_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'node_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'function_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'argument_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('isis_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('vendor_ext', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'IS-IS SRv6 Locator',
                'ordering': ('instance', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='isisflexalgo',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isisflexalgo',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='device',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='isis_instances',
                to='dcim.device',
            ),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='vrf',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='isis_instances',
                to='ipam.vrf',
            ),
        ),
        migrations.AddField(
            model_name='isisflexalgo',
            name='instance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flex_algos',
                to='netbox_routing.isisinstance',
            ),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='instance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='interfaces',
                to='netbox_routing.isisinstance',
            ),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='interface',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='isis_interfaces',
                to='dcim.interface',
            ),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isisinterfacelevel',
            name='interface',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='levels',
                to='netbox_routing.isisinterface',
            ),
        ),
        migrations.AddField(
            model_name='isisinterfacelevel',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isisinterfacelevel',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isislevel',
            name='instance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='levels',
                to='netbox_routing.isisinstance',
            ),
        ),
        migrations.AddField(
            model_name='isislevel',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isislevel',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isisprefixsid',
            name='interface',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prefix_sids',
                to='netbox_routing.isisinterface',
            ),
        ),
        migrations.AddField(
            model_name='isisprefixsid',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isisprefixsid',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='instance',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='segment_routing',
                to='netbox_routing.isisinstance',
            ),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isissetting',
            name='assigned_object_type',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(
                            ('app_label', 'netbox_routing'), ('model', 'isisinstance')
                        ),
                        models.Q(
                            ('app_label', 'netbox_routing'), ('model', 'isisinterface')
                        ),
                        _connector='OR',
                    )
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='isissetting',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isissetting',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='isissrv6locator',
            name='instance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='srv6_locators',
                to='netbox_routing.isisinstance',
            ),
        ),
        migrations.AddField(
            model_name='isissrv6locator',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='isissrv6locator',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(
                fields=('device', 'process_tag'),
                name='netbox_routing_isisinstance_device_process_tag_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisflexalgo',
            constraint=models.UniqueConstraint(
                fields=('instance', 'algo_id'),
                name='netbox_routing_isisflexalgo_instance_algo_id_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisflexalgo',
            constraint=models.CheckConstraint(
                condition=models.Q(('algo_id__gte', 128), ('algo_id__lte', 255)),
                name='netbox_routing_isisflexalgo_algo_id_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.UniqueConstraint(
                fields=('interface', 'address_family'),
                name='netbox_routing_isisinterface_interface_af_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisinterfacelevel',
            constraint=models.UniqueConstraint(
                fields=('interface', 'level'),
                name='netbox_routing_isisinterfacelevel_interface_level_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isislevel',
            constraint=models.UniqueConstraint(
                fields=('instance', 'level'),
                name='netbox_routing_isislevel_instance_level_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisprefixsid',
            constraint=models.UniqueConstraint(
                fields=('interface', 'algorithm'),
                name='netbox_routing_isisprefixsid_interface_algorithm_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isisprefixsid',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('algorithm', 0),
                    models.Q(('algorithm__gte', 128), ('algorithm__lte', 255)),
                    _connector='OR',
                ),
                name='netbox_routing_isisprefixsid_algorithm_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='isissetting',
            constraint=models.UniqueConstraint(
                fields=('assigned_object_type', 'assigned_object_id', 'key'),
                name='netbox_routing_isissettings_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isissetting',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('assigned_object_id__isnull', False),
                    ('assigned_object_type__isnull', False),
                ),
                name='netbox_routing_isissetting_assignment_required',
            ),
        ),
        migrations.AddConstraint(
            model_name='isissrv6locator',
            constraint=models.UniqueConstraint(
                fields=('instance', 'name'),
                name='netbox_routing_isissrv6locator_instance_name_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='isissrv6locator',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('algorithm', 0),
                    models.Q(('algorithm__gte', 128), ('algorithm__lte', 255)),
                    ('algorithm__isnull', True),
                    _connector='OR',
                ),
                name='netbox_routing_isissrv6locator_algorithm_range',
            ),
        ),
    ]
