# Generated by Django 6.1 on 2026-09-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0250_cooling_infrastructure'),
        ('extras', '0144_customfield_status'),
        ('ipam', '0097_merge_ipaddress_host_index_and_multi_protocol_services'),
        ('netbox_routing', '0033_isis'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspath',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='aspathentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bfdprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgpaddressfamily',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgppeer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgppeeraddressfamily',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgppeertemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgppolicytemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgprouter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgpscope',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgpsessiontemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='bgpsetting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='communitylist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='communitylistentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='customprefix',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='eigrpaddressfamily',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='eigrpinterface',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='eigrpnetwork',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='eigrprouter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isisflexalgo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isisinterface',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isisinterfacelevel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isislevel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isisprefixsid',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isissegmentrouting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isissetting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='isissrv6locator',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='ospfarea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='ospfinstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='ospfinterface',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='prefixlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='prefixlistentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='routemap',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='routemapentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner'),
        ),
    ]
