# Generated by Django 6.1 on 2026-09-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0033_isis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspath',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='bgppeeraddressfamily',
            options={
                'ordering': (
                    'assigned_object_type',
                    'assigned_object_id',
                    'address_family',
                    'pk',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='bgppeertemplate',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='bgpsetting',
            options={
                'ordering': ('assigned_object_type', 'assigned_object_id', 'key', 'pk')
            },
        ),
        migrations.AlterModelOptions(
            name='communitylistentry',
            options={'ordering': ('community_list', 'community', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='isisinterface',
            options={'ordering': ('instance', 'interface', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='isissetting',
            options={
                'ordering': ('assigned_object_type', 'assigned_object_id', 'key', 'pk')
            },
        ),
        migrations.AlterModelOptions(
            name='ospfarea',
            options={'ordering': ['area_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='ospfinstance',
            options={'ordering': ['vrf', 'router_id', 'process_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='prefixlist',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='routemap',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='staticroute',
            options={'ordering': ['vrf', 'prefix', 'metric', 'pk']},
        ),
    ]
