from django.urls import path, include

from netbox.views.generic import ObjectChangeLogView
from utilities.urls import get_model_urls

from . import views
from .models import *

urlpatterns = [
    path('routes/static/', views.StaticRouteListView.as_view(), name='staticroute_list'),
    path('routes/static/add/', views.StaticRouteEditView.as_view(), name='staticroute_add'),
    path('routes/static/import/', views.StaticRouteBulkImportView.as_view(), name='staticroute_bulk_import'),
    path('routes/static/edit/', views.StaticRouteBulkEditView.as_view(), name='staticroute_bulk_edit'),
    path('routes/static/delete/', views.StaticRouteBulkDeleteView.as_view(), name='staticroute_bulk_delete'),
    path('routes/static/<int:pk>/', include(get_model_urls('netbox_routing', 'staticroute'))),
    path('routes/static/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='staticroute_changelog', kwargs={'model': StaticRoute}),

    path('ospf/instance/', views.OSPFInstanceListView.as_view(), name='ospfinstance_list'),
    path('ospf/instance/add/', views.OSPFInstanceEditView.as_view(), name='ospfinstance_add'),
    path('ospf/instance/import/', views.OSPFInstanceBulkImportView.as_view(), name='ospfinstance_bulk_import'),
    path('ospf/instance/edit/', views.OSPFInstanceBulkEditView.as_view(), name='ospfinstance_bulk_edit'),
    path('ospf/instance/delete/', views.OSPFInstanceBulkDeleteView.as_view(), name='ospfinstance_bulk_delete'),
    path('ospf/instance/<int:pk>/', include(get_model_urls('netbox_routing', 'ospfinstance'))),
    path('ospf/instance/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='ospfinstance_changelog', kwargs={'model': OSPFInstance}),

    path('ospf/area/', views.OSPFAreaListView.as_view(), name='ospfarea_list'),
    path('ospf/area/add/', views.OSPFAreaEditView.as_view(), name='ospfarea_add'),
    path('ospf/area/import/', views.OSPFAreaBulkImportView.as_view(), name='ospfarea_bulk_import'),
    path('ospf/area/edit/', views.OSPFAreaBulkEditView.as_view(), name='ospfarea_bulk_edit'),
    path('ospf/area/delete/', views.OSPFAreaBulkDeleteView.as_view(), name='ospfarea_bulk_delete'),
    path('ospf/area/<int:pk>/', include(get_model_urls('netbox_routing', 'ospfarea'))),
    path('ospf/area/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='ospfarea_changelog', kwargs={'model': OSPFArea}),

    path('ospf/interface/', views.OSPFInterfaceListView.as_view(), name='ospfinterface_list'),
    path('ospf/interface/add/', views.OSPFInterfaceEditView.as_view(), name='ospfinterface_add'),
    path('ospf/interface/import/', views.OSPFInterfaceBulkImportView.as_view(), name='ospfinterface_bulk_import'),
    path('ospf/interface/edit/', views.OSPFInterfaceBulkEditView.as_view(), name='ospfinterface_bulk_edit'),
    path('ospf/interface/delete/', views.OSPFInterfaceBulkDeleteView.as_view(), name='ospfinterface_bulk_delete'),
    path('ospf/interface/<int:pk>/', include(get_model_urls('netbox_routing', 'ospfinterface'))),
    path('ospf/interface/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='ospfarea_changelog', kwargs={'model': OSPFInterface}),

    path('eigrp/router/', views.EIGRPRouterListView.as_view(), name='eigrprouter_list'),
    path('eigrp/router/add/', views.EIGRPRouterEditView.as_view(), name='eigrprouter_add'),
    path('eigrp/router/import/', views.EIGRPRouterBulkImportView.as_view(), name='eigrprouter_bulk_import'),
    path('eigrp/router/edit/', views.EIGRPRouterBulkEditView.as_view(), name='eigrprouter_bulk_edit'),
    path('eigrp/router/delete/', views.EIGRPRouterBulkDeleteView.as_view(), name='eigrprouter_bulk_delete'),
    path('eigrp/router/<int:pk>/', include(get_model_urls('netbox_routing', 'eigrprouter'))),
    path('eigrp/router/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='eigrprouter_changelog', kwargs={'model': EIGRPRouter}),

    path('eigrp/address-family/', views.EIGRPAddressFamilyListView.as_view(), name='eigrpaddressfamily_list'),
    path('eigrp/address-family/add/', views.EIGRPAddressFamilyEditView.as_view(), name='eigrpaddressfamily_add'),
    path('eigrp/address-family/import/', views.EIGRPAddressFamilyBulkImportView.as_view(), name='eigrpaddressfamily_bulk_import'),
    path('eigrp/address-family/edit/', views.EIGRPAddressFamilyBulkEditView.as_view(), name='eigrpaddressfamily_bulk_edit'),
    path('eigrp/address-family/delete/', views.EIGRPAddressFamilyBulkDeleteView.as_view(), name='eigrpaddressfamily_bulk_delete'),
    path('eigrp/address-family/<int:pk>/', include(get_model_urls('netbox_routing', 'eigrpaddressfamily'))),
    path('eigrp/address-family/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='eigrpaddressfamily_changelog', kwargs={'model': EIGRPAddressFamily}),

    path('eigrp/network/', views.EIGRPNetworkListView.as_view(), name='eigrpnetwork_list'),
    path('eigrp/network/add/', views.EIGRPNetworkEditView.as_view(), name='eigrpnetwork_add'),
    path('eigrp/network/import/', views.EIGRPNetworkBulkImportView.as_view(), name='eigrpnetwork_bulk_import'),
    path('eigrp/network/edit/', views.EIGRPNetworkBulkEditView.as_view(), name='eigrpnetwork_bulk_edit'),
    path('eigrp/network/delete/', views.EIGRPNetworkBulkDeleteView.as_view(), name='eigrpnetwork_bulk_delete'),
    path('eigrp/network/<int:pk>/', include(get_model_urls('netbox_routing', 'eigrpnetwork'))),
    path('eigrp/network/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='eigrpnetwork_changelog', kwargs={'model': EIGRPNetwork}),

    path('eigrp/interface/', views.EIGRPInterfaceListView.as_view(), name='eigrpinterface_list'),
    path('eigrp/interface/add/', views.EIGRPInterfaceEditView.as_view(), name='eigrpinterface_add'),
    path('eigrp/interface/import/', views.EIGRPInterfaceBulkImportView.as_view(), name='eigrpinterface_bulk_import'),
    path('eigrp/interface/edit/', views.EIGRPInterfaceBulkEditView.as_view(), name='eigrpinterface_bulk_edit'),
    path('eigrp/interface/delete/', views.EIGRPInterfaceBulkDeleteView.as_view(), name='eigrpinterface_bulk_delete'),
    path('eigrp/interface/<int:pk>/', include(get_model_urls('netbox_routing', 'eigrpinterface'))),
    path('eigrp/interface/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='eigrpinterface_changelog', kwargs={'model': EIGRPInterface}),

    path('bgp/router/', views.BGPRouterListView.as_view(), name='bgprouter_list'),
    path('bgp/router/add/', views.BGPRouterEditView.as_view(), name='bgprouter_add'),
    path('bgp/router/edit/', views.BGPRouterBulkEditView.as_view(), name='bgprouter_bulk_edit'),
    path('bgp/router/delete/', views.BGPRouterBulkDeleteView.as_view(), name='bgprouter_bulk_delete'),
    path('bgp/router/import/', views.BGPRouterBulkImportView.as_view(), name='bgprouter_bulk_import'),
    path('bgp/router/<int:pk>/', include(get_model_urls('netbox_routing', 'bgprouter'))),
    path('bgp/router/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgprouter_changelog', kwargs={'model': BGPRouter}),

    path('bgp/scope/', views.BGPScopeListView.as_view(), name='bgpscope_list'),
    path('bgp/scope/add/', views.BGPScopeEditView.as_view(), name='bgpscope_add'),
    path('bgp/scope/edit/', views.BGPScopeBulkEditView.as_view(), name='bgpscope_bulk_edit'),
    path('bgp/scope/delete/', views.BGPScopeBulkDeleteView.as_view(), name='bgpscope_bulk_delete'),
    path('bgp/scope/import/', views.BGPScopeBulkImportView.as_view(), name='bgpscope_bulk_import'),
    path('bgp/scope/<int:pk>/', include(get_model_urls('netbox_routing', 'bgpscope'))),
    path('bgp/router/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgpscope_changelog', kwargs={'model': BGPScope}),

    path('bgp/templates/session/', views.BGPSessionTemplateListView.as_view(), name='bgpsessiontemplate_list'),
    path('bgp/templates/session/add/', views.BGPSessionTemplateEditView.as_view(), name='bgpsessiontemplate_add'),
    path('bgp/templates/session/edit/', views.BGPSessionTemplateBulkEditView.as_view(), name='bgpsessiontemplate_bulk_edit'),
    path('bgp/templates/session/delete/', views.BGPSessionTemplateBulkDeleteView.as_view(), name='bgpsessiontemplate_bulk_delete'),
    path('bgp/templates/session/import/', views.BGPSessionTemplateBulkImportView.as_view(), name='bgpsessiontemplate_bulk_import'),
    path('bgp/templates/session/<int:pk>/', include(get_model_urls('netbox_routing', 'bgpsessiontemplate'))),
    path('bgp/templates/session/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgpsessiontemplate_changelog', kwargs={'model': BGPSessionTemplate}),

    path('bgp/templates/policy/', views.BGPPolicyTemplateListView.as_view(), name='bgppolicytemplate_list'),
    path('bgp/templates/policy/add/', views.BGPPolicyTemplateEditView.as_view(), name='bgppolicytemplate_add'),
    path('bgp/templates/policy/edit/', views.BGPPolicyTemplateBulkEditView.as_view(), name='bgppolicytemplate_bulk_edit'),
    path('bgp/templates/policy/delete/', views.BGPPolicyTemplateBulkDeleteView.as_view(), name='bgppolicytemplate_bulk_delete'),
    path('bgp/templates/policy/import/', views.BGPPolicyTemplateBulkImportView.as_view(), name='bgppolicytemplate_bulk_import'),
    path('bgp/templates/policy/<int:pk>/', include(get_model_urls('netbox_routing', 'bgppolicytemplate'))),
    path('bgp/templates/policy/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgppolicytemplate_changelog', kwargs={'model': BGPPolicyTemplate}),

    path('bgp/templates/peer/', views.BGPPeerTemplateListView.as_view(), name='bgppeertemplate_list'),
    path('bgp/templates/peer/add/', views.BGPPeerTemplateEditView.as_view(), name='bgppeertemplate_add'),
    path('bgp/templates/peer/edit/', views.BGPPeerTemplateBulkEditView.as_view(), name='bgppeertemplate_bulk_edit'),
    path('bgp/templates/peer/delete/', views.BGPPeerTemplateBulkDeleteView.as_view(), name='bgppeertemplate_bulk_delete'),
    path('bgp/templates/peer/import/', views.BGPPeerTemplateBulkImportView.as_view(), name='bgppeertemplate_bulk_import'),
    path('bgp/templates/peer/<int:pk>/', include(get_model_urls('netbox_routing', 'bgppeertemplate'))),
    path('bgp/templates/peer/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgppeertemplate_changelog', kwargs={'model': BGPPeerTemplate}),

    path('bgp/address-family/', views.BGPAddressFamilyListView.as_view(), name='bgpaddressfamily_list'),
    path('bgp/address-family/add/', views.BGPAddressFamilyEditView.as_view(), name='bgpaddressfamily_add'),
    path('bgp/address-family/edit/', views.BGPAddressFamilyBulkEditView.as_view(), name='bgpaddressfamily_bulk_edit'),
    path('bgp/address-family/delete/', views.BGPAddressFamilyBulkDeleteView.as_view(), name='bgpaddressfamily_bulk_delete'),
    path('bgp/address-family/import/', views.BGPAddressFamilyBulkImportView.as_view(), name='bgpaddressfamily_bulk_import'),
    path('bgp/address-family/<int:pk>/', include(get_model_urls('netbox_routing', 'bgpaddressfamily'))),
    path('bgp/address-family/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgpaddressfamily_changelog', kwargs={'model': BGPAddressFamily}),

    path('bgp/peer/', views.BGPPeerListView.as_view(), name='bgppeer_list'),
    path('bgp/peer/add/', views.BGPPeerEditView.as_view(), name='bgppeer_add'),
    path('bgp/peer/edit/', views.BGPPeerBulkEditView.as_view(), name='bgppeer_bulk_edit'),
    path('bgp/peer/delete/', views.BGPPeerBulkDeleteView.as_view(), name='bgppeer_bulk_delete'),
    path('bgp/peer/import/', views.BGPPeerBulkImportView.as_view(), name='bgppeer_bulk_import'),
    path('bgp/peer/<int:pk>/', include(get_model_urls('netbox_routing', 'bgppeer'))),
    path('bgp/peer/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgppeer_changelog', kwargs={'model': BGPPeer}),

    path('bgp/peer/address-family/', views.BGPPeerAddressFamilyListView.as_view(), name='bgppeeraddressfamily_list'),
    path('bgp/peer/address-family/add/', views.BGPPeerAddressFamilyEditView.as_view(), name='bgppeeraddressfamily_add'),
    path('bgp/peer/address-family/edit/', views.BGPPeerAddressFamilyBulkEditView.as_view(), name='bgppeeraddressfamily_bulk_edit'),
    path('bgp/peer/address-family/delete/', views.BGPPeerAddressFamilyBulkDeleteView.as_view(), name='bgppeeraddressfamily_bulk_delete'),
    path('bgp/peer/address-family/import/', views.BGPPeerAddressFamilyBulkImportView.as_view(), name='bgppeeraddressfamily_bulk_import'),
    path('bgp/peer/address-family/<int:pk>/', include(get_model_urls('netbox_routing', 'bgppeeraddressfamily'))),
    path('bgp/peer/address-family/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='bgppeeraddressfamily_changelog', kwargs={'model': BGPPeerAddressFamily}),

    path('prefix-list/', views.PrefixListListView.as_view(), name='prefixlist_list'),
    path('prefix-list/add/', views.PrefixListEditView.as_view(), name='prefixlist_add'),
    path('prefix-list/import/', views.PrefixListListView.as_view(), name='prefixlist_import'),
    path('prefix-list/<int:pk>/', include(get_model_urls('netbox_routing', 'prefixlist'))),
    path('prefix-list/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='prefixlist_changelog', kwargs={'model': PrefixList}),

    path('prefix-list/entry/', views.PrefixListEntryListView.as_view(), name='prefixlistentry_list'),
    path('prefix-list/entry/add/', views.PrefixListEntryEditView.as_view(), name='prefixlistentry_add'),
    path('prefix-list/entry/edit/', views.PrefixListEntryBulkEditView.as_view(), name='prefixlistentry_bulk_edit'),
    path('prefix-list/entry/delete/', views.PrefixListEntryBulkDeleteView.as_view(), name='prefixlistentry_bulk_delete'),
    #path('prefix-list-entry/import/', views.PrefixListEntryImportView.as_view(), name='prefixlistentry_import'),
    path('prefix-list/entry/<int:pk>/', include(get_model_urls('netbox_routing', 'prefixlistentry'))),
    path('prefix-list/entry/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='prefixlistentry_changelog', kwargs={'model': PrefixListEntry}),

    path('route-map/', views.RouteMapListView.as_view(), name='routemap_list'),
    path('route-map/add/', views.RouteMapEditView.as_view(), name='routemap_add'),
    # path('route-map/edit/', views.RouteMapBulkEditView.as_view(), name='routemap_bulk_edit'),
    # path('route-map/delete/', views.RouteMapBulkDeleteView.as_view(), name='routemap_bulk_delete'),
    # path('route-map/import/', views.RouteMapImportView.as_view(), name='routemap_import'),
    path('route-map/<int:pk>/', include(get_model_urls('netbox_routing', 'routemap'))),
    path('route-map/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='prefixlist_changelog', kwargs={'model': RouteMap}),

    path('route-map-entry/', views.RouteMapEntryListView.as_view(), name='routemapentry_list'),
    path('route-map-entry/add/', views.RouteMapEntryEditView.as_view(), name='routemapentry_add'),
    # path('route-map-entry/edit/', views.RouteMapEntryBulkEditView.as_view(), name='routemapentry_bulk_edit'),
    # path('route-map-entry/delete/', views.RouteMapEntryBulkDeleteView.as_view(), name='routemapentry_bulk_delete'),
    # path('route-map-entry/import/', views.RouteMapEntryListView.as_view(), name='routemapentry_import'),
    path('route-map-entry/<int:pk>/', include(get_model_urls('netbox_routing', 'routemapentry'))),
    path('route-map/entry/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='routemapentry_changelog', kwargs={'model': RouteMapEntry}),

    path('communitylist/', views.CommunityListListView.as_view(), name='communitylist_list'),
    path('communitylist/add/', views.CommunityListEditView.as_view(), name='communitylist_add'),
    path('communitylist/import/', views.CommunityListBulkImportView.as_view(), name='communitylist_bulk_import'),
    path('communitylist/edit/', views.CommunityListBulkEditView.as_view(), name='community_bulk_edit'),
    path('communitylist/delete/', views.CommunityListBulkDeleteView.as_view(), name='community_bulk_delete'),
    path('communitylist/<int:pk>/', include(get_model_urls('netbox_routing', 'communitylist'))),
    path('communitylist/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='communitylist_changelog', kwargs={'model': CommunityList}),

    path('community/', views.CommunityListView.as_view(), name='community_list'),
    path('community/add/', views.CommunityEditView.as_view(), name='community_add'),
    path('community/import/', views.CommunityBulkImportView.as_view(), name='community_bulk_import'),
    path('community/edit/', views.CommunityBulkEditView.as_view(), name='community_bulk_edit'),
    path('community/delete/', views.CommunityBulkDeleteView.as_view(), name='community_bulk_delete'),
    path('community/<int:pk>/', include(get_model_urls('netbox_routing', 'community'))),
    path('community/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='community_changelog', kwargs={'model': Community}),
]
